plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true

  Exclude:
    - "db/schema.rb"
    - "config/**/*"
    - "config.ru"
    - "bin/**/*"
    - "db/migrate/*"
    - "db/seeds.rb"
    - "tmp/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "**/*.txt"
    - "**/.keep"
    - "spec/rails_helper.rb"
    - "vendor/**/*"
    - "Rakefile"

  TargetRubyVersion: 3.2.2

Naming/RescuedExceptionsVariableName:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/PluckInWhere:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 35
  Exclude:
    - "**/*params.rb"
    - "spec/**/*"
    - 'lib/tasks/**/*.rake'

Metrics/ModuleLength:
  Exclude:
    - "**/*params.rb"

RSpec/NestedGroups:
  Max: 8

Layout/LineLength:
  Max: 140
  AllowURI: true
  URISchemes:
    - http
    - https
  AllowedPatterns:
    - '^\s*#'   # ignore comment lines
  Exclude:
    - "**/*params.rb"

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/requests/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/IndexedLet:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/services/scraper/*'
    - 'app/services/importer/*'
    - 'app/services/prophet_ratings/prediction_evaluator.rb'
    - 'app/services/prophet_ratings/team_season_stats_aggregator.rb'

Metrics/ClassLength:
  Max: 300

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - 'spec/requests/**/*'

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - 'app/services/scraper/*'

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'app/services/scraper/*'

Style/OpenStructUse:
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
