# frozen_string_literal: true

# Be sure to restart your server when you modify this file.
#
# This file eases the Rails 8.1 framework defaults upgrade. Keep these
# commented until the app is ready to opt into each behavior change. Once every
# setting below is enabled and verified, remove this file and set
# `config.load_defaults` to `8.1` in config/application.rb.
#
# See: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html

# Skip escaping HTML entities and line separators in JSON responses.
# Applications that want to keep the previous escaping behavior can set this to
# true.
# Rails.application.config.action_controller.escape_json_responses = false

# Skip escaping U+2028 LINE SEPARATOR and U+2029 PARAGRAPH SEPARATOR in JSON.
# Rails.application.config.active_support.escape_js_separators_in_json = false

# Raise when order-dependent finder methods such as `first` and `second` are
# called without order values and without implicit order columns to fall back on.
# Rails.application.config.active_record.raise_on_missing_required_finder_order_columns = true

# Raise for path-relative redirects such as `redirect_to "example.com"`.
# Rails.application.config.action_controller.action_on_path_relative_redirect = :raise

# Use a Ruby parser to track dependencies between Action View templates.
# Rails.application.config.action_view.render_tracker = :ruby

# Omit `autocomplete="off"` on hidden inputs generated by Rails form helpers.
# Rails.application.config.action_view.remove_hidden_field_autocomplete = true
