default: &default
  bundle_name: "v1.1-default"
  weighting:
    recency_decay_days: 60.0
    min_recency_weight: 0.75
    preseason_decay_days: 40
    min_preseason_weight: 0.1
  blowout:
    max_margin: 15
    cap_multiplier: 1.25
  home_court_advantage: 3.0
  home_court_adjusted_stats:
  - offensive_efficiency
  - defensive_efficiency
  ridge:
    alpha: 0.001
  anchor:
    weight: 0.05
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
